### ISSUE TITLE
Clone issue

### ISSUE THREAD

**Issue by IanaKhitsko** [Veetaha/mipz-practice-1#6]
https://github.com/Veetaha/mipz-practice-1/blob/5384646b3c545b8e48f041f00aaf76fe03a351de/src/calc.rs#L68

Why do we need to close keys here?

**Comment by Veetaha** [comment]
We have to clone the keys because this how Rust language's ownership system works.
We take the string (`country_name`) from the general map of countries and `insert()` it into the map `country -> coins`. To do that we have to either transfer the ownership or clone the value. The first is not possible because the general map is behind a shared reference `&`, so we must clone the keys.

https://github.com/Veetaha/mipz-practice-1/blob/96c3fd53f9e8009e46397b9ebdf3c273ae784aae/src/calc.rs#L68-L76

I hope this answers your question. Feel free to reopen if you have additional questions.
