### ISSUE TITLE
Null neighbors

### ISSUE THREAD

**Issue by IanaKhitsko** [Veetaha/mipz-practice-1#9]
https://github.com/Veetaha/mipz-practice-1/blob/5384646b3c545b8e48f041f00aaf76fe03a351de/src/calc.rs#L118-L122

What if any of the neighbors is null?

**Comment by Veetaha** [comment]
If the neighbors are `null`, then they won't be included, because `null` is represented as an empty iterator in this expression. Empty iterators will be ignored thanks to `.flatten()` combinator used here.

https://github.com/Veetaha/mipz-practice-1/blob/5384646b3c545b8e48f041f00aaf76fe03a351de/src/calc.rs#L118-L125

I hope this answers your question, if not, please feel free to reopen!
